<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Campaign;
use App\Models\Doctor;
use App\Models\Category;
use App\Models\Specialty;
use Carbon\Carbon;

class CampaignSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get first doctor and category for demo data
        $doctor = Doctor::first();
        $category = Category::first();
        $specialty = Specialty::first();

        if (!$doctor) {
            $this->command->info('No doctors found. Please create doctors first.');
            return;
        }

        $campaigns = [
            [
                'title' => 'Free Eye Check-up Camp',
                'description' => 'Comprehensive eye examination including vision testing, glaucoma screening, and cataract detection. Free consultation with experienced ophthalmologists.',
                'location' => 'Community Health Center, Mumbai',
                'latitude' => 19.0760,
                'longitude' => 72.8777,
                'start_date' => Carbon::now()->addDays(5),
                'end_date' => Carbon::now()->addDays(7),
                'start_time' => '09:00:00',
                'end_time' => '17:00:00',
                'camp_type' => 'medical',
                'registration_payment' => 0,
                'per_refer_cost' => 50,
                'amount' => 0,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543210',
                'expected_patients' => 150,
                'images' => ['campaigns/demo/eye-camp.jpg'],
                'thumbnail' => 'campaigns/demo/eye-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Vision testing, Eye pressure check, Retinal examination, Free spectacles for needy patients',
            ],
            [
                'title' => 'Diabetes Awareness & Screening Camp',
                'description' => 'Free diabetes screening camp with blood sugar testing, HbA1c testing, and dietary counseling. Expert endocrinologists will provide consultation.',
                'location' => 'City Hospital, Delhi',
                'latitude' => 28.7041,
                'longitude' => 77.1025,
                'start_date' => Carbon::now()->addDays(10),
                'end_date' => Carbon::now()->addDays(12),
                'start_time' => '08:00:00',
                'end_time' => '16:00:00',
                'camp_type' => 'medical',
                'registration_payment' => 100,
                'per_refer_cost' => 75,
                'amount' => 100,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543211',
                'expected_patients' => 200,
                'images' => ['campaigns/demo/diabetes-camp.jpg'],
                'thumbnail' => 'campaigns/demo/diabetes-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Blood sugar testing, HbA1c testing, Dietary counseling, Diabetes education, Free glucometer for qualifying patients',
            ],
            [
                'title' => 'Women\'s Health Check-up Camp',
                'description' => 'Comprehensive women\'s health screening including breast examination, cervical cancer screening, and reproductive health counseling.',
                'location' => 'Women\'s Medical Center, Bangalore',
                'latitude' => 12.9716,
                'longitude' => 77.5946,
                'start_date' => Carbon::now()->addDays(15),
                'end_date' => Carbon::now()->addDays(16),
                'start_time' => '10:00:00',
                'end_time' => '18:00:00',
                'camp_type' => 'medical',
                'registration_payment' => 150,
                'per_refer_cost' => 100,
                'amount' => 150,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543212',
                'expected_patients' => 120,
                'images' => ['campaigns/demo/womens-health-camp.jpg'],
                'thumbnail' => 'campaigns/demo/womens-health-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Breast examination, Pap smear, Reproductive health counseling, Pregnancy consultation, Family planning guidance',
            ],
            [
                'title' => 'Heart Health Screening Camp',
                'description' => 'Free cardiac screening with ECG, blood pressure monitoring, cholesterol testing, and consultation with cardiologists.',
                'location' => 'Cardiology Institute, Chennai',
                'latitude' => 13.0827,
                'longitude' => 80.2707,
                'start_date' => Carbon::now()->addDays(20),
                'end_date' => Carbon::now()->addDays(22),
                'start_time' => '07:00:00',
                'end_time' => '15:00:00',
                'camp_type' => 'medical',
                'registration_payment' => 0,
                'per_refer_cost' => 80,
                'amount' => 0,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543213',
                'expected_patients' => 180,
                'images' => ['campaigns/demo/heart-camp.jpg'],
                'thumbnail' => 'campaigns/demo/heart-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'ECG testing, Blood pressure monitoring, Cholesterol testing, Heart health consultation, Lifestyle counseling',
            ],
            [
                'title' => 'Pediatric Vaccination Camp',
                'description' => 'Free vaccination camp for children with all essential vaccines. Pediatric consultation and growth monitoring included.',
                'location' => 'Children\'s Hospital, Kolkata',
                'latitude' => 22.5726,
                'longitude' => 88.3639,
                'start_date' => Carbon::now()->addDays(25),
                'end_date' => Carbon::now()->addDays(26),
                'start_time' => '09:30:00',
                'end_time' => '17:30:00',
                'camp_type' => 'medical',
                'registration_payment' => 50,
                'per_refer_cost' => 60,
                'amount' => 50,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543214',
                'expected_patients' => 250,
                'images' => ['campaigns/demo/pediatric-camp.jpg'],
                'thumbnail' => 'campaigns/demo/pediatric-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Childhood vaccinations, Growth monitoring, Developmental assessment, Nutrition counseling, Health education for parents',
            ],
            [
                'title' => 'Dental Care Camp',
                'description' => 'Comprehensive dental check-up with cleaning, fluoride treatment, and oral health education. Free dental consultation and treatment for children.',
                'location' => 'Dental College, Pune',
                'latitude' => 18.5204,
                'longitude' => 73.8567,
                'start_date' => Carbon::now()->addDays(30),
                'end_date' => Carbon::now()->addDays(31),
                'start_time' => '08:30:00',
                'end_time' => '16:30:00',
                'camp_type' => 'medical',
                'registration_payment' => 75,
                'per_refer_cost' => 40,
                'amount' => 75,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543215',
                'expected_patients' => 160,
                'images' => ['campaigns/demo/dental-camp.jpg'],
                'thumbnail' => 'campaigns/demo/dental-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Dental examination, Teeth cleaning, Fluoride treatment, Oral health education, Basic dental treatments',
            ],
            [
                'title' => 'Mental Health Awareness Camp',
                'description' => 'Mental health screening and counseling camp with psychiatrists and psychologists. Stress management workshops and therapy sessions.',
                'location' => 'Mental Health Center, Hyderabad',
                'latitude' => 17.3850,
                'longitude' => 78.4867,
                'start_date' => Carbon::now()->addDays(35),
                'end_date' => Carbon::now()->addDays(37),
                'start_time' => '10:00:00',
                'end_time' => '18:00:00',
                'camp_type' => 'medical',
                'registration_payment' => 200,
                'per_refer_cost' => 120,
                'amount' => 200,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543216',
                'expected_patients' => 100,
                'images' => ['campaigns/demo/mental-health-camp.jpg'],
                'thumbnail' => 'campaigns/demo/mental-health-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Mental health screening, Individual counseling, Group therapy, Stress management workshops, Mental wellness education',
            ],
            [
                'title' => 'Bone & Joint Health Camp',
                'description' => 'Orthopedic consultation camp with bone density testing, joint examination, and physiotherapy guidance for elderly patients.',
                'location' => 'Orthopedic Hospital, Jaipur',
                'latitude' => 26.9124,
                'longitude' => 75.7873,
                'start_date' => Carbon::now()->addDays(40),
                'end_date' => Carbon::now()->addDays(41),
                'start_time' => '08:00:00',
                'end_time' => '17:00:00',
                'camp_type' => 'medical',
                'registration_payment' => 125,
                'per_refer_cost' => 90,
                'amount' => 125,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543217',
                'expected_patients' => 140,
                'images' => ['campaigns/demo/bone-joint-camp.jpg'],
                'thumbnail' => 'campaigns/demo/bone-joint-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Bone density testing, Joint examination, X-ray screening, Physiotherapy consultation, Exercise guidance',
            ],
            [
                'title' => 'Skin & Dermatology Camp',
                'description' => 'Comprehensive skin screening camp with dermatological consultation, skin cancer screening, and treatment for common skin conditions.',
                'location' => 'Dermatology Clinic, Ahmedabad',
                'latitude' => 23.0225,
                'longitude' => 72.5714,
                'start_date' => Carbon::now()->addDays(45),
                'end_date' => Carbon::now()->addDays(46),
                'start_time' => '09:00:00',
                'end_time' => '18:00:00',
                'camp_type' => 'medical',
                'registration_payment' => 100,
                'per_refer_cost' => 70,
                'amount' => 100,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543218',
                'expected_patients' => 130,
                'images' => ['campaigns/demo/skin-camp.jpg'],
                'thumbnail' => 'campaigns/demo/skin-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Skin examination, Skin cancer screening, Acne treatment, Cosmetic dermatology consultation, Skin care education',
            ],
            [
                'title' => 'General Health Check-up Camp',
                'description' => 'Comprehensive general health screening with blood tests, physical examination, and health counseling for all age groups.',
                'location' => 'Community Center, Lucknow',
                'latitude' => 26.8467,
                'longitude' => 80.9462,
                'start_date' => Carbon::now()->addDays(50),
                'end_date' => Carbon::now()->addDays(52),
                'start_time' => '07:30:00',
                'end_time' => '16:30:00',
                'camp_type' => 'medical',
                'registration_payment' => 150,
                'per_refer_cost' => 85,
                'amount' => 150,
                'doctor_id' => $doctor->id,
                'category_id' => $category?->id,
                'specializations' => [$specialty?->id ?? 1],
                'contact_number' => '+91 9876543219',
                'expected_patients' => 220,
                'images' => ['campaigns/demo/general-health-camp.jpg'],
                'thumbnail' => 'campaigns/demo/general-health-camp-thumb.jpg',
                'video' => null,
                'approval_status' => 'approved',
                'service_in_camp' => 'Complete blood count, Physical examination, Blood pressure check, BMI calculation, Health counseling, Lifestyle guidance',
            ],
        ];

        foreach ($campaigns as $campaignData) {
            Campaign::create($campaignData);
        }

        $this->command->info('10 demo campaigns created successfully!');
    }
}
