#!/bin/bash
# Manual SSH Deployment Script for Hostinger

echo "🚀 FreeDoctor Manual Deployment Guide"
echo "======================================"
echo ""
echo "1. SSH into your Hostinger server:"
echo "   ssh u150415685@in-mum-web1823.main-hosting.eu"
echo ""
echo "2. Navigate to your domain directory:"
echo "   cd /home/u150415685/domains/YOUR_DOMAIN.com/public_html"
echo ""
echo "3. Clear existing files (backup first if needed):"
echo "   rm -rf *"
echo ""
echo "4. Clone the repository:"
echo "   git clone https://github.com/Mytechdata/freedoctor.git ."
echo ""
echo "5. Set up Laravel:"
echo "   cp .env.example .env"
echo "   nano .env  # Edit with your database details"
echo ""
echo "6. Install dependencies:"
echo "   composer install --no-dev --optimize-autoloader"
echo "   npm install --production"
echo "   npm run build"
echo ""
echo "7. Configure Laravel:"
echo "   php artisan key:generate"
echo "   php artisan migrate --force"
echo "   php artisan config:cache"
echo "   php artisan route:cache"
echo "   php artisan view:cache"
echo ""
echo "8. Set permissions:"
echo "   chmod -R 755 storage"
echo "   chmod -R 755 bootstrap/cache"
echo ""
echo "9. Update document root in Hostinger panel to:"
echo "   /domains/YOUR_DOMAIN.com/public_html/public"
echo ""
echo "✅ Deployment Complete!"
