name: Deploy to Hostinger

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_sqlite, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install Composer dependencies
      run: composer install --no-progress --no-suggest --no-interaction --prefer-dist --optimize-autoloader --no-dev
      
    - name: Install NPM dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Run tests (optional)
      run: php artisan test --env=testing
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ':memory:'
        
    - name: Deploy to Hostinger
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: in-mum-web1823.main-hosting.eu
        username: u150415685
        key: ${{ secrets.HOSTINGER_SSH_KEY }}
        script: |
          cd /home/u150415685/domains/your-domain.com/public_html
          git pull origin main
          composer install --no-dev --optimize-autoloader
          npm install --production
          npm run build
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache
          
    - name: Notify deployment success
      if: success()
      run: echo "🚀 Deployment completed successfully!"
      
    - name: Notify deployment failure
      if: failure()
      run: echo "❌ Deployment failed!"
